#!/bin/bash
source ~/.bash_profile

hg pull
hg up -C

# mix deps.get
# mix release.clean --implode --no-confirm
mix deps.get

MIX_ENV=prod node node_modules/bower/bin/bower install
MIX_ENV=prod node node_modules/brunch/bin/brunch build
MIX_ENV=prod mix do phoenix.digest, compile
MIX_ENV=prod mix release --env=prod --upgrade --verbose
